services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rssfed
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rssfed
    volumes:
      - rssfed-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rssfed"] 
      interval: 10s
      start_period: 30s
    restart: always
volumes:
  rssfed-db: