onlyBuiltDependencies:
  - leveldown

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

allowBuilds:
  leveldown: set this to true or false
